server:
  #端口号
  port: 80
  tomcat:
    max-threads: 1000
    max-connections: 2000
    uri-encoding: UTF-8
  servlet:
    context-path: /api

#org:
#  quartz:
#    threadPool:
#      threadCount: 20
spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://47.103.195.19:3306/seat?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 792d46b6b473
    HikariPool:
      validation-query: SELECT 1
      max-lifetime: 30000
      min-idle: 50
      maximum-pool-size: 100
      auto-commit: true
      pool-name: pandaHikariPool
      time-between-eviction-runs-millis: 18800
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    #    解决懒加载
    open-in-view: true
  redis:
    host: 47.103.195.19
    password: panda
    port: 6379
    # 连接超时时间
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    cache:
      # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
      type: redis
logging:
#  path: ./out/logs
  file: "//var//log//seat//daily.log"
  level:
    root: info
    #异常的日志等级设定为最高
  pattern:
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

wx:
  config:
    appId: wx371d49c958b3c21e
    appSecret: 37a0b0b75208be548d11c4a9ce395a2d
